apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "course-app.fullname" . }}
  labels:
    {{- include "course-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    {{- toYaml .Values.strategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "course-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "course-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
          envFrom:
            - configMapRef:
                name: {{ include "course-app.fullname" . }}-config
          env:
            {{- if .Values.appRedis.auth.enabled }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.appRedis.auth.existingSecret }}
                  key: {{ .Values.appRedis.auth.existingSecretPasswordKey }}
            - name: APP_REDIS_URL
              value: "redis://:$(REDIS_PASSWORD)@{{ .Values.appRedis.host }}:{{ .Values.appRedis.port }}/{{ .Values.appRedis.database }}"
            {{- else }}
            - name: APP_REDIS_URL
              value: "redis://{{ .Values.appRedis.host }}:{{ .Values.appRedis.port }}/{{ .Values.appRedis.database }}"
            {{- end }}
          {{- with .Values.probes.liveness }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.probes.readiness }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
